### ISSUE TITLE
[BUG] paramiko ftp service _Connection wrapper missing remove/unlink

### ISSUE THREAD

**Issue by dgpaci** [genropy/genropy#848]
## Problem Description

The new `paramiko/service.py` SFTP service introduced in #847 / PR #847 wraps `paramiko.SFTPClient` in a custom `_Connection` class. The wrapper exposes `listdir`, `isdir`, `stat`, `get`, `put`, `close` — but **not** `remove` / `unlink`.

`pysftp.Connection` (the class returned by the existing `pysftp/service.py`) exposes both `remove` and `unlink`. Any caller that downloads a file and then deletes it from the remote — a natural pattern for any polling/drain workflow — works against `pysftp/service` but breaks against `paramiko/service` with:

```
'_Connection' object has no attribute 'remove'
```

This makes `paramiko/service` non drop-in: instances that switch implementation to work around the Ed25519 issue (#845) lose functionality silently until they hit it at runtime.

### Root cause

[`projects/gnrcore/packages/sys/resources/services/ftp/paramiko/service.py`](https://github.com/genropy/genropy/blob/845-bug-pysftp-service-fails-with-ed25519-and-other-modern-private-keys/projects/gnrcore/packages/sys/resources/services/ftp/paramiko/service.py) defines `_Connection` with a curated method set and does not forward `remove`/`unlink` to the underlying `paramiko.SFTPClient`, which does support them.

## Reproduction Steps

1. Configure a `sys.service` of type `ftp` with `implementation=paramiko/service` against any reachable SSH server (Ed25519 key OK).
2. From any code path that uses the service:
   ```python
   service = self.page.getService('ftp', service_name='<svc>')
   with service() as conn:
       files = conn.listdir()
       conn.remove(files[0])   # <- AttributeError
   ```
3. Observed: `'_Connection' object has no attribute 'remove'`.
   Expected: file removed from the remote, mirroring `pysftp.Connection.remove(...)`.

## Environment

- genropy: branch `845-bug-pysftp-service-fails-with-ed25519-and-other-modern-private-keys` (PR #847)
- Python: 3.12
- paramiko: 4.x
- OS: macOS / Linux (platform-independent)

## Proposed Fix

Add to `_Connection`:

```python
def remove(self, remotepath):
    self._sftp.remove(remotepath)

unlink = remove
```

Both names because `pysftp.Connection` exposes both — keeping the wrapper drop-in compatible.

A broader option, if the goal is full parity with `pysftp.Connection`, is to delegate any unknown attribute to `self._sftp` via `__getattr__`. The narrow fix above is enough to unblock the SFTP polling use case without expanding the surface area beyond what's needed.
