### ISSUE TITLE
Wrong handle for missing dependencies

### ISSUE THREAD

**Issue by cgabriel** [genropy/genropy#1285]
While veryfing erpy-ext repo build, a dependency issue has been raised:

https://github.com/genropy/genropy/blob/8193e5c6c70fa7703a5a747e8483b926fe8fc470/gnrpy/gnr/xtnd/gnrpandas.py#L66-L74

If the dependency (numpy) is missing (it's not a framework strict dependency) the inevitable result is:

```
 File "/home/genro/genropy_projects/erpy-ext/packages/erpy_shop/model/vendita_riepilogo.py", line 1, in <module>
    from gnr.xtnd.gnrpandas import GnrDbDataframe
  File "/usr/local/lib/python3.11/site-packages/gnr/xtnd/gnrpandas.py", line 74, in <module>
    AGGFUNCDICT = {'sum':np.sum,'mean':np.mean,'count':len,'min':np.min,'max':np.max}
                         ^^^^^^
AttributeError: 'bool' object has no attribute 'sum'
```

because 'np' is simply reassigned to 'False' when not present, and then used in AGGFUNCDICT. 

Similar issues can also raise with the `pandas` module reassigned to False as well, and then used later on.

Since adding numpy as a dependencies will increase the framework image, I suggest to verify if these dependencies are really needed, and refactor the gnrpandas.py accordingly. Or, if really needed, inform all erpy variants using the GnrDbDataframe to add these dependencies to their requirements.txt file.

Issue introduced in e5c85efd1e on 2017-01-31
