### ISSUE TITLE
[BUG] the form treats both transport failure classes as one, and dismisses itself when nobody has told the user anything

### ISSUE THREAD

**Issue by genro** [genropy/genropy#1350]
Follow-up to #1311, which lands the mechanism this refines. Related to #1319, which produces the information this needs.

## What #1311 settled

A failed load, save or delete no longer reads as a success: the chain flips on the failure, the store skips `loaded`/`saved`/`deleted`, the form restores its state, and a code the platform already surfaces leaves the form silent so the user is not told twice. That rule is right and is not in question here.

## What it cannot yet get right

The form sees one code, `rpc_error`, for two transport outcomes that the rpc layer treats oppositely.

`classifyHttpError` (`gnrjs/gnr_d11/js/genro_rpc.js:183-198`) returns `server_unavailable` for status 0, 502, 503, 504 and timeout, and `application_error` for everything else. `errorHandler` (`:523-534`) then sends `application_error` to `genro.dev.handleRpcHttpError`, which speaks immediately, while `server_unavailable` goes to `_onServerError()`, which shows nothing at all until five seconds of continuous failure have elapsed (`:200-208`, `SERVER_UNAVAILABLE_THRESHOLD`).

Both reach the form as `undefined`, and `rpcError` maps both to `rpc_error`. So the single rule is right for one half and wrong for the other:

- `application_error` — the platform has spoken. The form staying silent is correct.
- `server_unavailable`, inside the five-second window — nobody has spoken, and the form dismisses itself with no explanation. The user loses their context and has no way to know why.

## Suggested direction

Two steps, in this order.

1. **Stop dismissing on `rpc_error`.** Restore state, publish `onLoadFailed`, and leave the form where it is. If the server really is down the lock screen arrives at five seconds and explains it globally, better than the form could; if it was one dropped request the user simply retries. A form that vanishes with nothing said is the worst of the available outcomes, worse than a stale form and worse than being told twice.

2. **Carry the classification through, then decide per class.** Once the rpc layer delivers transport failures as envelope errors (#1319), the form can distinguish `application_error` from `server_unavailable` and choose for each, instead of choosing once for both. At that point step 1 can be revisited on evidence rather than on the least-wrong default.

## Also to fix here

`gnrjs/gnr_d11/js/genro_frm.js`, `load_recordCluster`: the `dbstoreOnDeferred` callback is registered before the result guard. On a form with `dbstoreField` set and no parent-store row value, an envelope error arrives as a plain object, so `result.getValue()` throws — the chain flips through the exception rather than through `rpcFailure`, the failure descriptor is lost, and the form is dismissed even for `gnrsilent`, which is exactly what the silent branch exists to prevent. Reproduced against the #1311 head: `onLoadFailed` carries `result.getValue is not a function` and the form is dismissed. Moving the guard's `addCallback` above the `dbstoreOnDeferred` block fixes it.

Separately, `save_recordCluster` still guards with `if (result)`, so a `null` result leaves `savedPkey` undefined on that one store while the `rpc` and `document` stores keep the current pkey. Identical on `develop`, so not introduced by #1311, but it is the one store where "a null save keeps the current pkey" does not hold.
